[package]
name = "rusoto-ceph-test"
version = "0.1.0"
authors = ["Peter Gerber <peter@arbitrary.ch>"]

[dependencies]
hyper = "0.10"
rusoto_core = "*"
rusoto_credential = "*"
rusoto_s3 = "*"
tokio-core = "*"
